//
// Identifiant.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Identifiant: JSONEncodable {

    public var typeIdentifiant: String?
    public var valeur: String?
    public var cleSI: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["typeIdentifiant"] = self.typeIdentifiant
        nillableDictionary["valeur"] = self.valeur
        nillableDictionary["cleSI"] = self.cleSI

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

