//
// MoyenCom.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class MoyenCom: JSONEncodable {

    public var valeur: String?
    public var cleSI: String?
    public var identifiant: Bool?
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["valeur"] = self.valeur
        nillableDictionary["cleSI"] = self.cleSI
        nillableDictionary["identifiant"] = self.identifiant
        nillableDictionary["type"] = self.type

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

