//
// SendOTPOutput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SendOTPOutput: JSONEncodable {

    public var identifiantTechnique: String?
    public var idOtp: String?
    public var codeOTP: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["identifiantTechnique"] = self.identifiantTechnique
        nillableDictionary["idOtp"] = self.idOtp
        nillableDictionary["codeOTP"] = self.codeOTP

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

