//
// SendOTPInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SendOTPInput: JSONEncodable {

    public var marque: String?
    public var identifiantTechnique: String?
    public var identifiantPersonneSI: String?
    public var cleMoyenCom: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["marque"] = self.marque
        nillableDictionary["identifiantTechnique"] = self.identifiantTechnique
        nillableDictionary["identifiantPersonneSI"] = self.identifiantPersonneSI
        nillableDictionary["cleMoyenCom"] = self.cleMoyenCom

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

