//
// SendTemporyPasswordOutput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SendTemporyPasswordOutput: JSONEncodable {

    public var identifiantTechnique: String?
    public var motDePasse: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["identifiantTechnique"] = self.identifiantTechnique
        nillableDictionary["motDePasse"] = self.motDePasse

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

