//
// UpdatePasswordInput.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UpdatePasswordInput: JSONEncodable {

    public var motDePasse: String?
    public var cleSI: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["motDePasse"] = self.motDePasse
        nillableDictionary["cleSI"] = self.cleSI

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

